spring:
  shell:
    interactive:
      enabled: true
  main:
    banner-mode: off
    web-application-type: none
  application:
    name: crud_projeto
  data:
    mongodb:
      host: localhost
      port: 27017
      database: agenda
server:
  port: 3000
logging:
  level:
    root: off










